version: '3.8'

services:
  api:
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm run start:dev
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - sportpal-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - sportpal-network
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}

networks:
  sportpal-network:
    driver: bridge

volumes:
  mongodb_data: