name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  deploy:
    if: github.event_name == 'push' || (github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      # - name: Run lint
      #   run: pnpm lint
  
      # - name: Run tests
      #   run: pnpm test

      - name: Build project
        run: pnpm build

      - name: Deploy to Netlify
        run: pnpm netlify deploy --prod --dir=build
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  delete-branch:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref != 'main'
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete branch
        run: |
          branch=${{ github.event.pull_request.head.ref }}
          if [ "$branch" != "main" ]; then
            git push origin --delete $branch
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}