name: Deploy to Netlify

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm lint
  
      - name: Run tests
        run: pnpm test

      - name: Build project
        run: pnpm build  


      - name: Deploy to Netlify
        run: npx netlify deploy --prod --dir=build  
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}